import { z } from 'zod';

export const merchantSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  slug: z.string().min(1, 'Slug is required'),
  description: z.string().optional().nullable(),
  logo_media_id: z.union([z.string().uuid(), z.literal('')]).optional().nullable(),
  favicon_media_id: z.union([z.string().uuid(), z.literal('')]).optional().nullable(),
  website: z.string().url('Invalid website URL').or(z.literal('')).optional().nullable(),
  support_email: z.string().email('Invalid email').or(z.literal('')).optional().nullable(),
  country: z.string().optional().nullable(),
  currency: z.string().optional().nullable(),
  shipping_regions: z.union([z.string(), z.array(z.string())]).optional().nullable(),
  return_policy_url: z.string().url('Invalid return policy URL').or(z.literal('')).optional().nullable(),
  affiliate_network: z.string().optional().nullable(),
  default_commission: z.number().min(0).max(100).optional().nullable(),
  cookie_duration: z.number().int().min(0).optional().nullable(),
  tracking_method: z.string().optional().nullable(),
  featured: z.boolean().default(false),
  display_order: z.number().int().default(0),
  priority: z.number().int().default(0),
  seo_title: z.string().optional().nullable(),
  seo_description: z.string().optional().nullable(),
  status: z.enum(['draft', 'published', 'archived']).default('draft'),
});

export const affiliateProgramSchema = z.object({
  merchant_id: z.string().uuid('Merchant is required'),
  program_name: z.string().min(1, 'Program name is required'),
  affiliate_network: z.string().optional().nullable(),
  network_dashboard_url: z.string().url('Invalid dashboard URL').or(z.literal('')).optional().nullable(),
  commission_type: z.string().optional().nullable(),
  commission_value: z.number().min(0).optional().nullable(),
  cookie_duration: z.number().int().min(0).optional().nullable(),
  approval_required: z.boolean().default(false),
  minimum_payout: z.number().min(0).optional().nullable(),
  payment_frequency: z.string().optional().nullable(),
  tracking_template: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  program_status: z.enum(['active', 'inactive', 'paused']).default('active'),
});

export const productMerchantSchema = z.object({
  product_id: z.string().uuid('Product is required'),
  merchant_id: z.string().uuid('Merchant is required'),
  affiliate_program_id: z.union([z.string().uuid(), z.literal('')]).optional().nullable(),
  affiliate_url: z.string().url('Invalid affiliate URL'),
  deep_link: z.string().url('Invalid deep link URL').or(z.literal('')).optional().nullable(),
  merchant_product_id: z.string().optional().nullable(),
  sku: z.string().optional().nullable(),
  buy_button_text: z.string().optional().nullable(),
  current_price: z.number().min(0).optional().nullable(),
  original_price: z.number().min(0).optional().nullable(),
  currency: z.string().default('INR'),
  availability: z.enum(['In Stock', 'Limited Stock', 'Out of Stock', 'Preorder', 'Discontinued']).default('In Stock'),
  estimated_delivery: z.string().optional().nullable(),
  free_shipping: z.boolean().default(false),
  coupon_available: z.boolean().default(false),
  coupon_code: z.string().optional().nullable(),
  merchant_rating: z.number().min(0).max(5).optional().nullable(),
  featured: z.boolean().default(false),
  priority: z.number().int().default(0),
  status: z.enum(['active', 'inactive']).default('active'),
});
